"""Changes fields

Revision ID: 045beb151140
Revises: ec766ef8ae97
Create Date: 2023-05-18 20:04:55.722126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '045beb151140'
down_revision = 'ec766ef8ae97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('validation',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_column('validation_in_progress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_in_progress', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.alter_column('validation',
               existing_type=sa.String(length=64),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    # ### end Alembic commands ###
