"""relacionamento de seed e round

Revision ID: 09bddaea5f96
Revises: e6a4be2feb0c
Create Date: 2023-05-23 02:25:12.462005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bddaea5f96'
down_revision = 'e6a4be2feb0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'round', ['round_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('round_id')

    # ### end Alembic commands ###
