"""New fields into Team Model

Revision ID: 1e1ce73a4b14
Revises: 5611c064dad6
Create Date: 2023-05-17 19:34:13.506582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1ce73a4b14'
down_revision = '5611c064dad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validationInProgress', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('validation', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('unplaced', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('unplaced')
        batch_op.drop_column('validation')
        batch_op.drop_column('validationInProgress')

    # ### end Alembic commands ###
