"""Snake case in Team field

Revision ID: 66622a242ad4
Revises: 1e1ce73a4b14
Create Date: 2023-05-18 16:32:43.996821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66622a242ad4'
down_revision = '1e1ce73a4b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validation_in_progress', sa.Boolean(), nullable=True))
        batch_op.drop_column('validationInProgress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validationInProgress', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('validation_in_progress')

    # ### end Alembic commands ###
