"""Change Team time column

Revision ID: e0ffa1d6208c
Revises: 045beb151140
Create Date: 2023-05-22 01:03:33.017833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0ffa1d6208c'
down_revision = '045beb151140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
