"""Time and points in Team Table

Revision ID: ec766ef8ae97
Revises: 66622a242ad4
Create Date: 2023-05-18 17:02:21.932805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec766ef8ae97'
down_revision = '66622a242ad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('time')
        batch_op.drop_column('points')

    # ### end Alembic commands ###
