"""Knockout column

Revision ID: fd12ad0ccd34
Revises: 8f6bedbaba86
Create Date: 2023-05-25 12:51:59.485682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd12ad0ccd34'
down_revision = '8f6bedbaba86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knockout_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('knockout_points')

    # ### end Alembic commands ###
